class HTMLError(Exception): ...
class ElementNotFound(HTMLError): ...

class AccessError(Exception):
    def __init__(self, *args: object, cause="TOKEN and bot safety") -> None:
        self.args = args
        self.cause = cause
        
class FunctionNotAllowedError(AccessError): ...

class NewsError(Exception): ...